// @ts-nocheck -- skip type checking
import * as docs_6 from "../content/docs/sdk-generator/index.mdx?collection=docs&hash=1759494814801"
import * as docs_5 from "../content/docs/http-adapters/usage.mdx?collection=docs&hash=1759494814801"
import * as docs_4 from "../content/docs/http-adapters/overview.mdx?collection=docs&hash=1759494814801"
import * as docs_3 from "../content/docs/engine/overview.mdx?collection=docs&hash=1759494814801"
import * as docs_2 from "../content/docs/engine/configuration.mdx?collection=docs&hash=1759494814801"
import * as docs_1 from "../content/docs/index.mdx?collection=docs&hash=1759494814801"
import * as docs_0 from "../content/docs/getting-started.mdx?collection=docs&hash=1759494814801"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"getting-started.mdx","fullPath":"content/docs/getting-started.mdx"}, data: docs_0 }, { info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: docs_1 }, { info: {"path":"engine/configuration.mdx","fullPath":"content/docs/engine/configuration.mdx"}, data: docs_2 }, { info: {"path":"engine/overview.mdx","fullPath":"content/docs/engine/overview.mdx"}, data: docs_3 }, { info: {"path":"http-adapters/overview.mdx","fullPath":"content/docs/http-adapters/overview.mdx"}, data: docs_4 }, { info: {"path":"http-adapters/usage.mdx","fullPath":"content/docs/http-adapters/usage.mdx"}, data: docs_5 }, { info: {"path":"sdk-generator/index.mdx","fullPath":"content/docs/sdk-generator/index.mdx"}, data: docs_6 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"pages":["index","getting-started","---Core Engine---","engine","---HTTP Adapters---","http-adapters","---Automation---","sdk-generator"]}}, {"info":{"path":"engine/meta.json","fullPath":"content/docs/engine/meta.json"},"data":{"title":"Engine","pages":["overview","configuration"],"description":"Core ReAuth engine configuration and lifecycle guidance.","root":true}}, {"info":{"path":"http-adapters/meta.json","fullPath":"content/docs/http-adapters/meta.json"},"data":{"title":"HTTP Adapters","pages":["overview","usage"],"description":"Integrate ReAuth with your transport layer and expose REST endpoints.","root":true}}, {"info":{"path":"sdk-generator/meta.json","fullPath":"content/docs/sdk-generator/meta.json"},"data":{"title":"SDK Generator","pages":["index"],"description":"Generate typed clients from a running ReAuth adapter.","root":true}}])